# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];
  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "ahci"
        "usbhid"
        "usb_storage"
        "sd_mod"
      ];
      kernelModules = [ ];
    };
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
  };
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/0ebec014-2ee1-40ef-956c-e8e2c7f0a33b";
      fsType = "ext4";
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/C074-BE26";
      fsType = "vfat";
    };
    "/mnt/ssd" = {
      device = "/dev/disk/by-uuid/64CC0DFCCC0DC8EE";
      fsType = "ntfs";
    };
  };
  swapDevices = [
    { device = "/dev/disk/by-uuid/3eadf6b5-b45f-4766-9dcd-4ff53aed4417"; }
  ];
  nixpkgs = {
    hostPlatform = lib.mkDefault "x86_64-linux";
  };
  hardware = {
    cpu = {
      amd = {
        updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
      };
    };
  };
}
