name: push
on:
  workflow_dispatch:
  push:
  pull_request_review:

jobs:
  lint:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Access private repository
        uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets.GH_PRIVATE_KEY }}
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install git git-crypt
      - uses: DeterminateSystems/nix-installer-action@v12
      - run: git config --global --add safe.directory "${PWD}"
      - run: echo "$GIT_CRYPT_KEY" | base64 -d | git-crypt unlock -
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - run: nix flake check
